### ISSUE TITLE
Wireframes for front page

### ISSUE THREAD

**Issue by bodhiprice** [woodwarddesign/merlo-farming-group#25]
![mfg - front page - desktop - v2](https://cloud.githubusercontent.com/assets/2105211/3614006/f430dd84-0dbc-11e4-9bf7-bd2cd315dd65.png)
![mfg - front page - tablet](https://cloud.githubusercontent.com/assets/2105211/3614009/f92d3648-0dbc-11e4-9f7a-21a66ab291b1.png)
![mfg - front page - mobile](https://cloud.githubusercontent.com/assets/2105211/3614011/fdb6717a-0dbc-11e4-8588-b8aafef1fda4.png)
![gauges-front](https://cloud.githubusercontent.com/assets/2105211/3614014/022e2dd8-0dbd-11e4-950a-75fd449eee7f.png)

**Comment by bodhiprice** [comment]
These are out for client review.

**Comment by bodhiprice** [comment]
@DirectorWho client approved with modifications. Let me know what you think. Mostly it seems like I can just use his notes and get started.

Approval Needed: Home page sketches
gino@merlofarminggroup.com gino@merlofarminggroup.com Thu, Jul 17, 2014 at 12:47 PM
To: John Hannah john@woodwarddesigngroup.com
Cc: Thomas Thackery thomas@woodwarddesigngroup.com, Scott Johnson scott@woodwarddesigngroup.com
Guys please find attached the layout approval for development.

look forward to seeing it come to life.

thank you.

Gino Fiori
Merlo Farming Group

![7-14-2014-layout-1](https://cloud.githubusercontent.com/assets/2105211/3616584/0360b834-0dd5-11e4-8308-be9a3c59875c.jpg)

**Comment by DirectorWho** [comment]
I agree. The only thing that might need a format update is reducing the
weather panels down to 1.

**Comment by bodhiprice** [comment]
@DirectorWho OK, I can get started on the front page Panels layout and you can update the wireframe accordingly. I will start with just some sample blocks to demonstrate layout and add real features as they come together.
