### ISSUE TITLE
Design :: Weather 

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/merlo-farming-group#4]
Here are screenshots from an iPHone app called DarkSky for inspiration. 
![image-0](https://cloud.githubusercontent.com/assets/7529130/3137908/62c131b6-e862-11e3-817f-284a5059e3b4.jpg)

![image-1](https://cloud.githubusercontent.com/assets/7529130/3137909/62c3b350-e862-11e3-8f2c-71f990cb368d.jpg)

![image-2](https://cloud.githubusercontent.com/assets/7529130/3137910/62c3cc00-
e862-11e3-983c-23f685cf5cce.jpg)

![image-3](https://cloud.githubusercontent.com/assets/7529130/3137912/62c44ef0-e862-11e3-86f2-0829539cc1bd.jpg)

![image-4](https://cloud.githubusercontent.com/assets/7529130/3137913/62c5889c-e862-11e3-9bcf-7c178d83703e.jpg)

![image-5](https://cloud.githubusercontent.com/assets/7529130/3137911/62c42c90-e862-11e3-8bcf-853108d7f960.jpg)

![image-6](https://cloud.githubusercontent.com/assets/7529130/3137914/62d17418-e862-11e3-95a9-9fdf8ff9d6b6.jpg)

![image-7](https://cloud.githubusercontent.com/assets/7529130/3137916/62d40ade-e862-11e3-8ce2-83c382564743.jpg)

**Comment by thomas-thackery** [comment]
Closing. Refer to #60
