### ISSUE TITLE
Design :: Market Page

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/merlo-farming-group#5]
Here are some screenshots form Mike on how to possibly display market information from NASS (see project brief). 

![image-8](https://cloud.githubusercontent.com/assets/7529130/3137929/e1ec3bd4-e862-11e3-8018-52adf447ae19.jpg)
![image-9](https://cloud.githubusercontent.com/assets/7529130/3137930/e1ec950c-e862-11e3-898d-cfc71870dad8.jpg)
![image-10](https://cloud.githubusercontent.com/assets/7529130/3137931/e1ed350c-e862-11e3-9b72-f58af4a1efce.jpg)
![image-11](https://cloud.githubusercontent.com/assets/7529130/3137934/e1f03d42-e862-11e3-8739-6461a1c55291.jpg)
![image-12](https://cloud.githubusercontent.com/assets/7529130/3137932/e1ee460e-e862-11e3-9ede-80024a1f7857.jpg)
![image-13](https://cloud.githubusercontent.com/assets/7529130/3137933/e1ef3b90-e862-11e3-8d15-9e8832b0cad2.jpg)

**Comment by thomas-thackery** [comment]
no longer a dedicated page. closing per consensus
